Friendshipv1
maosan132/Social-media-website pull request #2
Opened 2020-09-03 22:06 UTC by yahir91

In this milestone, we have to be able to make friends.

- A model friendship with the corresponding associations was added.
- The option to add a friend was added to the views.
- A user can accept and reject a friend request.
- A new page was called friendship was created where you can see your friend request.

2020-09-07 20:06 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Lets change that `Already friends` to `unfriend`
![12](https://user-images.githubusercontent.com/23278161/92414577-c7cb0100-f14c-11ea-9d4c-a1f562d2739d.png)
- [ ] Let's write unit and integration test for all components using Rspec and capybara
- [ ] Check comment below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-07 20:06 UTC, kobiyoyo commented on app/controllers/friendships_controller.rb
> +  end
Everything connected with data processing should be encapsulated in models and used in controllers.

2020-09-16 21:37 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- Please fix all linter errors BEFORE requesting a review.
- Organize your tests in different folders - `spec/controllers`, `spec/models`, etc.
- Write tests for all your models. Don't forget to test associations and validations. _HINT: Use shoulda_matchers gem._
- Please DO NOT commit commented codes. You have commented codes in ` spec/auth_spec.rb` and `spec/friend_spec.rb`.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-09-16 23:01 UTC, stratospherique approved these changes
### Great job on implementing the suggested changes :clap: Congrats, the milestone is approved :heavy_check_mark: You may merge :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-09-18 22:58 UTC, merged